spring:
  application:
    name: zone-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 0
    host: localhost
    password:
    port: 6379

zuul:
  routes:
    back:
      path: /user/**
      serviceId: zone-user

    blog:
      path: /blog/**
      serviceId: zone-blog

    dms:
      path: /dms/**
      serviceId: zone-dms

    ams:
      path: /ams/**
      serviceId: zone-ams
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  #ignored-patterns: /user/login


server:
  port: 8765
eureka:
  instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#  security:
#      user:
#          name: admin
#          password: admin
#          role: USER
#
#  gate:
#    ignore:
#      startWith: /static
#      contain: .
#    oauth:
#      prefix: /api

#    jwt:
#      secret: Xe*g@1jda
#      expiration: 7200
#      header: access-token